ALTER TABLE product
    ADD COLUMN IF NOT EXISTS sale_mode VARCHAR(20) NOT NULL DEFAULT 'UNIT';

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS quantity_uom VARCHAR(20) NOT NULL DEFAULT 'UNIT';

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS quantity_precision INT NOT NULL DEFAULT 0;

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS open_price_min NUMERIC(14, 2);

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS open_price_max NUMERIC(14, 2);

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS open_price_requires_reason BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE product
SET sale_mode = 'UNIT',
    quantity_uom = 'UNIT',
    quantity_precision = 0,
    open_price_requires_reason = FALSE
WHERE sale_mode IS NULL
   OR quantity_uom IS NULL
   OR quantity_precision IS NULL
   OR open_price_requires_reason IS NULL;

ALTER TABLE product
    ADD CONSTRAINT ck_product_sale_mode_supported
        CHECK (sale_mode IN ('UNIT', 'WEIGHT', 'OPEN_PRICE'));

ALTER TABLE product
    ADD CONSTRAINT ck_product_quantity_uom_supported
        CHECK (quantity_uom IN ('UNIT', 'KILOGRAM', 'GRAM', 'POUND'));

ALTER TABLE product
    ADD CONSTRAINT ck_product_sale_mode_policy
        CHECK (
            (sale_mode = 'UNIT'
                AND quantity_uom = 'UNIT'
                AND quantity_precision = 0
                AND open_price_min IS NULL
                AND open_price_max IS NULL
                AND open_price_requires_reason = FALSE)
            OR
            (sale_mode = 'WEIGHT'
                AND quantity_uom IN ('KILOGRAM', 'GRAM', 'POUND')
                AND quantity_precision BETWEEN 1 AND 3
                AND open_price_min IS NULL
                AND open_price_max IS NULL
                AND open_price_requires_reason = FALSE)
            OR
            (sale_mode = 'OPEN_PRICE'
                AND quantity_uom = 'UNIT'
                AND quantity_precision = 0
                AND open_price_min IS NOT NULL
                AND open_price_max IS NOT NULL
                AND open_price_min <= open_price_max)
        );

CREATE TABLE IF NOT EXISTS open_price_entry_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    actor_username VARCHAR(80) NOT NULL,
    entered_price NUMERIC(14, 2) NOT NULL,
    reason VARCHAR(255) NULL,
    correlation_id VARCHAR(64) NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_open_price_entry_audit_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_open_price_entry_audit_product_occurred
    ON open_price_entry_audit (product_id, occurred_at);

INSERT INTO app_permission (code, description)
SELECT 'OPEN_PRICE_ENTRY', 'Allows manual open-price entry operations'
WHERE NOT EXISTS (SELECT 1 FROM app_permission WHERE code = 'OPEN_PRICE_ENTRY');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM app_role r
JOIN app_permission p ON p.code = 'OPEN_PRICE_ENTRY'
WHERE r.code = 'MANAGER'
  AND NOT EXISTS (
    SELECT 1
    FROM role_permission rp
    WHERE rp.role_id = r.id
      AND rp.permission_id = p.id
);
