CREATE TABLE IF NOT EXISTS tax_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    tax_rate_percent NUMERIC(7, 4) NOT NULL DEFAULT 0.0000,
    is_zero_rated BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tax_group_merchant FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_tax_group_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT ck_tax_group_rate_percent CHECK (tax_rate_percent >= 0.0000 AND tax_rate_percent <= 100.0000),
    CONSTRAINT ck_tax_group_zero_rated_policy CHECK (is_zero_rated = FALSE OR tax_rate_percent = 0.0000)
);

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS tax_group_id BIGINT NULL;

ALTER TABLE product
    ADD CONSTRAINT fk_product_tax_group
        FOREIGN KEY (tax_group_id) REFERENCES tax_group (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_product_tax_group
    ON product (tax_group_id);

CREATE TABLE IF NOT EXISTS store_tax_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    tax_group_id BIGINT NOT NULL,
    tax_mode VARCHAR(20) NOT NULL,
    is_exempt BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMP NULL,
    effective_to TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_tax_rule_store_location FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_store_tax_rule_tax_group FOREIGN KEY (tax_group_id) REFERENCES tax_group (id) ON DELETE CASCADE,
    CONSTRAINT ck_store_tax_rule_tax_mode CHECK (tax_mode IN ('INCLUSIVE', 'EXCLUSIVE')),
    CONSTRAINT ck_store_tax_rule_effective_window CHECK (
        effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to
    )
);

CREATE INDEX IF NOT EXISTS idx_store_tax_rule_lookup
    ON store_tax_rule (store_location_id, tax_group_id, is_active, effective_from, effective_to);
