CREATE TABLE IF NOT EXISTS rounding_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    tender_type VARCHAR(20) NOT NULL,
    rounding_method VARCHAR(20) NOT NULL,
    increment_amount NUMERIC(10, 2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rounding_policy_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT uk_rounding_policy_store_tender UNIQUE (store_location_id, tender_type),
    CONSTRAINT ck_rounding_policy_tender_type CHECK (tender_type IN ('CASH', 'CARD')),
    CONSTRAINT ck_rounding_policy_method CHECK (rounding_method IN ('NEAREST', 'UP', 'DOWN')),
    CONSTRAINT ck_rounding_policy_increment CHECK (increment_amount > 0.00)
);

CREATE INDEX IF NOT EXISTS idx_rounding_policy_store_active
    ON rounding_policy (store_location_id, is_active);
