CREATE TABLE IF NOT EXISTS receipt_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    series_code VARCHAR(40) NOT NULL,
    number_policy VARCHAR(20) NOT NULL DEFAULT 'GAPLESS',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipt_series_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_series_terminal_device
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE CASCADE,
    CONSTRAINT uk_receipt_series_terminal UNIQUE (terminal_device_id),
    CONSTRAINT uk_receipt_series_store_code UNIQUE (store_location_id, series_code),
    CONSTRAINT ck_receipt_series_number_policy CHECK (number_policy IN ('GAPLESS', 'GAPPED'))
);

CREATE INDEX IF NOT EXISTS idx_receipt_series_store_terminal
    ON receipt_series (store_location_id, terminal_device_id);

CREATE TABLE IF NOT EXISTS receipt_sequence (
    series_id BIGINT PRIMARY KEY,
    next_number BIGINT NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipt_sequence_series
        FOREIGN KEY (series_id) REFERENCES receipt_series (id) ON DELETE CASCADE,
    CONSTRAINT ck_receipt_sequence_next_number_positive CHECK (next_number > 0)
);

CREATE TABLE IF NOT EXISTS receipt_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    number BIGINT NOT NULL,
    receipt_number VARCHAR(80) NOT NULL,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipt_header_series
        FOREIGN KEY (series_id) REFERENCES receipt_series (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_header_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_header_terminal_device
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE CASCADE,
    CONSTRAINT uk_receipt_header_series_number UNIQUE (series_id, number),
    CONSTRAINT uk_receipt_header_receipt_number UNIQUE (receipt_number),
    CONSTRAINT ck_receipt_header_number_positive CHECK (number > 0)
);

CREATE INDEX IF NOT EXISTS idx_receipt_header_terminal_issued
    ON receipt_header (terminal_device_id, issued_at);
