CREATE TABLE IF NOT EXISTS discount_reason_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NULL,
    code VARCHAR(40) NOT NULL,
    description VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discount_reason_code_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_discount_reason_code_merchant_code UNIQUE (merchant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_discount_reason_code_lookup
    ON discount_reason_code (merchant_id, code, is_active);

CREATE TABLE IF NOT EXISTS discount_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NULL,
    reason_code_id BIGINT NOT NULL,
    context_key VARCHAR(64) NOT NULL,
    discount_scope VARCHAR(20) NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value DECIMAL(14, 4) NOT NULL,
    note VARCHAR(255),
    applied_by_username VARCHAR(80) NOT NULL,
    removed_by_username VARCHAR(80),
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discount_application_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_discount_application_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_discount_application_reason_code
        FOREIGN KEY (reason_code_id) REFERENCES discount_reason_code (id),
    CONSTRAINT ck_discount_application_scope CHECK (discount_scope IN ('LINE', 'CART')),
    CONSTRAINT ck_discount_application_type CHECK (discount_type IN ('FIXED', 'PERCENTAGE')),
    CONSTRAINT ck_discount_application_value_positive CHECK (discount_value > 0),
    CONSTRAINT ck_discount_application_scope_product CHECK (
        (discount_scope = 'LINE' AND product_id IS NOT NULL)
        OR (discount_scope = 'CART' AND product_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_discount_application_context_active
    ON discount_application (store_location_id, context_key, is_active, applied_at);

INSERT INTO app_permission (code, description)
SELECT 'DISCOUNT_OVERRIDE', 'Allows high-threshold discount overrides'
WHERE NOT EXISTS (SELECT 1 FROM app_permission WHERE code = 'DISCOUNT_OVERRIDE');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM app_role r
JOIN app_permission p ON p.code = 'DISCOUNT_OVERRIDE'
WHERE r.code = 'MANAGER'
  AND NOT EXISTS (
    SELECT 1
    FROM role_permission rp
    WHERE rp.role_id = r.id
      AND rp.permission_id = p.id
);

INSERT INTO discount_reason_code (merchant_id, code, description, is_active)
SELECT NULL, 'PRICE_MATCH', 'Manual price match discount', TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM discount_reason_code
    WHERE merchant_id IS NULL
      AND UPPER(code) = 'PRICE_MATCH'
);

INSERT INTO discount_reason_code (merchant_id, code, description, is_active)
SELECT NULL, 'DAMAGED_ITEM', 'Damaged or quality issue adjustment', TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM discount_reason_code
    WHERE merchant_id IS NULL
      AND UPPER(code) = 'DAMAGED_ITEM'
);
