CREATE TABLE IF NOT EXISTS promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    priority INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_promotion_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_promotion_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT ck_promotion_priority_non_negative CHECK (priority >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_merchant_active_priority
    ON promotion (merchant_id, is_active, priority, id);

CREATE TABLE IF NOT EXISTS promotion_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL,
    rule_type VARCHAR(30) NOT NULL,
    target_product_id BIGINT NULL,
    discount_value DECIMAL(14, 4) NOT NULL,
    min_quantity DECIMAL(14, 3),
    min_subtotal DECIMAL(14, 2),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_promotion_rule_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotion (id) ON DELETE CASCADE,
    CONSTRAINT fk_promotion_rule_target_product
        FOREIGN KEY (target_product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT ck_promotion_rule_type CHECK (rule_type IN ('PRODUCT_PERCENTAGE', 'CART_FIXED')),
    CONSTRAINT ck_promotion_rule_discount_positive CHECK (discount_value > 0),
    CONSTRAINT ck_promotion_rule_percentage_range CHECK (
        rule_type <> 'PRODUCT_PERCENTAGE' OR discount_value <= 100.0000
    ),
    CONSTRAINT ck_promotion_rule_target_scope CHECK (
        (rule_type = 'PRODUCT_PERCENTAGE' AND target_product_id IS NOT NULL)
        OR (rule_type = 'CART_FIXED' AND target_product_id IS NULL)
    ),
    CONSTRAINT ck_promotion_rule_minimums CHECK (
        (min_quantity IS NULL OR min_quantity > 0)
        AND (min_subtotal IS NULL OR min_subtotal >= 0)
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_rule_promotion_active
    ON promotion_rule (promotion_id, is_active, rule_type, id);

CREATE TABLE IF NOT EXISTS promotion_window (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL,
    starts_at TIMESTAMP NULL,
    ends_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_promotion_window_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotion (id) ON DELETE CASCADE,
    CONSTRAINT ck_promotion_window_range CHECK (
        starts_at IS NULL OR ends_at IS NULL OR starts_at <= ends_at
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_window_lookup
    ON promotion_window (promotion_id, is_active, starts_at, ends_at, id);
