CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    display_name VARCHAR(160),
    invoice_required BOOLEAN NOT NULL DEFAULT FALSE,
    credit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_customer_merchant_active
    ON customer (merchant_id, is_active, id);

CREATE TABLE IF NOT EXISTS customer_tax_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    document_value VARCHAR(80) NOT NULL,
    document_value_normalized VARCHAR(80) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_tax_identity_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_tax_identity_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_customer_tax_identity_merchant_document
        UNIQUE (merchant_id, document_type, document_value_normalized),
    CONSTRAINT uk_customer_tax_identity_customer_type
        UNIQUE (customer_id, document_type)
);

CREATE INDEX IF NOT EXISTS idx_customer_tax_identity_lookup
    ON customer_tax_identity (merchant_id, document_type, document_value_normalized, is_active);

CREATE TABLE IF NOT EXISTS customer_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    contact_type VARCHAR(20) NOT NULL,
    contact_value VARCHAR(120) NOT NULL,
    contact_value_normalized VARCHAR(120) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_contact_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_contact_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_customer_contact_customer_type_value
        UNIQUE (customer_id, contact_type, contact_value_normalized),
    CONSTRAINT ck_customer_contact_type
        CHECK (contact_type IN ('EMAIL', 'PHONE'))
);

CREATE INDEX IF NOT EXISTS idx_customer_contact_lookup
    ON customer_contact (merchant_id, contact_type, contact_value_normalized, is_active, customer_id);
