CREATE TABLE IF NOT EXISTS loyalty_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    operation_type VARCHAR(20) NOT NULL,
    reference VARCHAR(80) NOT NULL,
    requested_points INT,
    points_delta INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    provider_code VARCHAR(40) NOT NULL,
    provider_reference VARCHAR(80),
    message VARCHAR(255),
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loyalty_event_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT fk_loyalty_event_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_loyalty_event_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
    CONSTRAINT ck_loyalty_event_operation_type
        CHECK (operation_type IN ('EARN', 'REDEEM')),
    CONSTRAINT ck_loyalty_event_status
        CHECK (status IN ('APPLIED', 'DISABLED', 'UNAVAILABLE', 'REJECTED')),
    CONSTRAINT ck_loyalty_event_requested_points_positive
        CHECK (requested_points IS NULL OR requested_points > 0),
    CONSTRAINT ck_loyalty_event_requested_points_by_operation
        CHECK (
            (operation_type = 'EARN' AND requested_points IS NULL)
            OR (operation_type = 'REDEEM' AND requested_points IS NOT NULL)
        ),
    CONSTRAINT ck_loyalty_event_points_delta_direction
        CHECK (
            (operation_type = 'EARN' AND points_delta >= 0)
            OR (operation_type = 'REDEEM' AND points_delta <= 0)
        )
);

CREATE INDEX IF NOT EXISTS idx_loyalty_event_customer_processed
    ON loyalty_event (customer_id, processed_at, id);

CREATE INDEX IF NOT EXISTS idx_loyalty_event_store_processed
    ON loyalty_event (store_location_id, processed_at, id);
