CREATE TABLE IF NOT EXISTS customer_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_group_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_customer_group_merchant_code
        UNIQUE (merchant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_customer_group_merchant_active
    ON customer_group (merchant_id, is_active, code, id);

CREATE TABLE IF NOT EXISTS customer_group_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_group_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_group_assignment_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_group_assignment_group
        FOREIGN KEY (customer_group_id) REFERENCES customer_group (id) ON DELETE CASCADE,
    CONSTRAINT uk_customer_group_assignment_customer_group
        UNIQUE (customer_id, customer_group_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_group_assignment_customer_active
    ON customer_group_assignment (customer_id, is_active, customer_group_id);

ALTER TABLE price_book
    ADD COLUMN IF NOT EXISTS customer_group_id BIGINT;

ALTER TABLE price_book
    ADD CONSTRAINT fk_price_book_customer_group
        FOREIGN KEY (customer_group_id) REFERENCES customer_group (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_price_book_customer_group_active_window
    ON price_book (customer_group_id, is_active, effective_from, effective_to, id);
