CREATE TABLE IF NOT EXISTS sale_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_user_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    pricing_at TIMESTAMP NOT NULL,
    subtotal_net NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_tax NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_gross NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    rounding_adjustment NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_payable NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_cart_cashier_user
        FOREIGN KEY (cashier_user_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_cart_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_cart_terminal_device
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE RESTRICT,
    CONSTRAINT ck_sale_cart_status
        CHECK (status IN ('ACTIVE', 'CHECKED_OUT', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_sale_cart_store_status_updated
    ON sale_cart (store_location_id, status, updated_at, id);

CREATE INDEX IF NOT EXISTS idx_sale_cart_terminal_status_updated
    ON sale_cart (terminal_device_id, status, updated_at, id);

CREATE INDEX IF NOT EXISTS idx_sale_cart_cashier_status_updated
    ON sale_cart (cashier_user_id, status, updated_at, id);

CREATE TABLE IF NOT EXISTS sale_cart_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    line_key VARCHAR(64) NULL,
    quantity NUMERIC(13, 3) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    net_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    gross_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    open_price_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_cart_line_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_cart_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_cart_line_cart_line_number
        UNIQUE (cart_id, line_number),
    CONSTRAINT uk_sale_cart_line_cart_line_key
        UNIQUE (cart_id, line_key),
    CONSTRAINT ck_sale_cart_line_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT ck_sale_cart_line_unit_price_non_negative
        CHECK (unit_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_cart_line_cart_lookup
    ON sale_cart_line (cart_id, line_number, id);

CREATE INDEX IF NOT EXISTS idx_sale_cart_line_product_lookup
    ON sale_cart_line (product_id, cart_id);
