ALTER TABLE sale_cart DROP CONSTRAINT IF EXISTS ck_sale_cart_status;

ALTER TABLE sale_cart
    ADD CONSTRAINT ck_sale_cart_status
        CHECK (status IN ('ACTIVE', 'PARKED', 'EXPIRED', 'CHECKED_OUT', 'CANCELLED'));

CREATE TABLE IF NOT EXISTS parked_cart_reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    reference_code VARCHAR(48) NOT NULL,
    parked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    parked_by_user_id BIGINT NULL,
    resumed_at TIMESTAMP NULL,
    resumed_by_user_id BIGINT NULL,
    cancelled_at TIMESTAMP NULL,
    cancelled_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_parked_cart_reference_cart UNIQUE (cart_id),
    CONSTRAINT uk_parked_cart_reference_code UNIQUE (reference_code),
    CONSTRAINT fk_parked_cart_reference_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT fk_parked_cart_reference_parked_by
        FOREIGN KEY (parked_by_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_parked_cart_reference_resumed_by
        FOREIGN KEY (resumed_by_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_parked_cart_reference_cancelled_by
        FOREIGN KEY (cancelled_by_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT ck_parked_cart_reference_expiry
        CHECK (expires_at > parked_at)
);

CREATE INDEX IF NOT EXISTS idx_parked_cart_reference_expiry
    ON parked_cart_reference (expires_at, cart_id);

CREATE INDEX IF NOT EXISTS idx_parked_cart_reference_parked_at
    ON parked_cart_reference (parked_at, cart_id);

CREATE TABLE IF NOT EXISTS sale_cart_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    actor_user_id BIGINT NULL,
    actor_username VARCHAR(80) NULL,
    terminal_device_id BIGINT NULL,
    correlation_id VARCHAR(100) NULL,
    detail VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_cart_event_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_cart_event_actor
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_sale_cart_event_terminal
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE SET NULL,
    CONSTRAINT ck_sale_cart_event_type
        CHECK (event_type IN ('PARKED', 'RESUMED', 'CANCELLED', 'EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_sale_cart_event_cart_created
    ON sale_cart_event (cart_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_sale_cart_event_type_created
    ON sale_cart_event (event_type, created_at, id);
