CREATE TABLE IF NOT EXISTS void_reason_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NULL,
    code VARCHAR(40) NOT NULL,
    description VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_void_reason_code_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_void_reason_code_merchant_code UNIQUE (merchant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_void_reason_code_lookup
    ON void_reason_code (merchant_id, code, is_active);

CREATE TABLE IF NOT EXISTS sale_override_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    line_id BIGINT NULL,
    event_type VARCHAR(20) NOT NULL,
    reason_code_id BIGINT NULL,
    reason_code VARCHAR(40) NOT NULL,
    note VARCHAR(255) NULL,
    before_unit_price NUMERIC(14, 2) NULL,
    after_unit_price NUMERIC(14, 2) NULL,
    approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by_user_id BIGINT NULL,
    approved_by_username VARCHAR(80) NULL,
    approved_at TIMESTAMP NULL,
    actor_user_id BIGINT NULL,
    actor_username VARCHAR(80) NULL,
    terminal_device_id BIGINT NULL,
    correlation_id VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_override_event_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_override_event_reason
        FOREIGN KEY (reason_code_id) REFERENCES void_reason_code (id) ON DELETE SET NULL,
    CONSTRAINT fk_sale_override_event_approved_by
        FOREIGN KEY (approved_by_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_sale_override_event_actor
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_sale_override_event_terminal
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE SET NULL,
    CONSTRAINT ck_sale_override_event_type
        CHECK (event_type IN ('LINE_VOID', 'PRICE_OVERRIDE', 'CART_VOID'))
);

CREATE INDEX IF NOT EXISTS idx_sale_override_event_cart_created
    ON sale_override_event (cart_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_sale_override_event_type_created
    ON sale_override_event (event_type, created_at, id);

INSERT INTO void_reason_code (merchant_id, code, description, is_active)
SELECT NULL, 'CUSTOMER_REQUEST', 'Customer requested cart or line void', TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM void_reason_code
    WHERE merchant_id IS NULL
      AND UPPER(code) = 'CUSTOMER_REQUEST'
);

INSERT INTO void_reason_code (merchant_id, code, description, is_active)
SELECT NULL, 'SCAN_ERROR', 'Incorrect scan or duplicate item correction', TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM void_reason_code
    WHERE merchant_id IS NULL
      AND UPPER(code) = 'SCAN_ERROR'
);

INSERT INTO void_reason_code (merchant_id, code, description, is_active)
SELECT NULL, 'PRICE_MATCH', 'Manager-approved price match override', TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM void_reason_code
    WHERE merchant_id IS NULL
      AND UPPER(code) = 'PRICE_MATCH'
);
