CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    tax_identifier VARCHAR(80),
    tax_identifier_normalized VARCHAR(80),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_merchant_code
        UNIQUE (merchant_id, code),
    CONSTRAINT uk_supplier_merchant_tax_identifier
        UNIQUE (merchant_id, tax_identifier_normalized)
);

CREATE INDEX IF NOT EXISTS idx_supplier_merchant_active_code
    ON supplier (merchant_id, is_active, code, id);

CREATE TABLE IF NOT EXISTS supplier_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    contact_type VARCHAR(20) NOT NULL,
    contact_value VARCHAR(160) NOT NULL,
    contact_value_normalized VARCHAR(160) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_contact_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_contact_supplier_type_value
        UNIQUE (supplier_id, contact_type, contact_value_normalized),
    CONSTRAINT ck_supplier_contact_type
        CHECK (contact_type IN ('EMAIL', 'PHONE'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_contact_supplier_active
    ON supplier_contact (supplier_id, is_active, contact_type, id);

CREATE TABLE IF NOT EXISTS supplier_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    payment_term_days INTEGER,
    credit_limit NUMERIC(14, 2),
    notes VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_terms_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_terms_supplier
        UNIQUE (supplier_id),
    CONSTRAINT ck_supplier_terms_payment_days
        CHECK (payment_term_days IS NULL OR payment_term_days >= 0),
    CONSTRAINT ck_supplier_terms_credit_limit
        CHECK (credit_limit IS NULL OR credit_limit >= 0)
);
