CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    total_payable NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_allocated NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_tendered NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    change_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_cart
        UNIQUE (cart_id),
    CONSTRAINT ck_payment_total_payable_non_negative
        CHECK (total_payable >= 0),
    CONSTRAINT ck_payment_total_allocated_non_negative
        CHECK (total_allocated >= 0),
    CONSTRAINT ck_payment_total_tendered_non_negative
        CHECK (total_tendered >= 0),
    CONSTRAINT ck_payment_change_non_negative
        CHECK (change_amount >= 0),
    CONSTRAINT ck_payment_allocated_matches_payable
        CHECK (total_allocated = total_payable),
    CONSTRAINT ck_payment_tendered_not_less_than_allocated
        CHECK (total_tendered >= total_allocated),
    CONSTRAINT ck_payment_change_consistency
        CHECK (change_amount = (total_tendered - total_allocated))
);

CREATE INDEX IF NOT EXISTS idx_payment_cart_created
    ON payment (cart_id, created_at, id);

CREATE TABLE IF NOT EXISTS payment_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    tender_type VARCHAR(20) NOT NULL,
    allocated_amount NUMERIC(14, 2) NOT NULL,
    tendered_amount NUMERIC(14, 2) NOT NULL,
    change_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    reference VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_allocation_payment
        FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_allocation_payment_sequence
        UNIQUE (payment_id, sequence_number),
    CONSTRAINT ck_payment_allocation_tender_type
        CHECK (tender_type IN ('CASH', 'CARD')),
    CONSTRAINT ck_payment_allocation_allocated_positive
        CHECK (allocated_amount > 0),
    CONSTRAINT ck_payment_allocation_tendered_non_negative
        CHECK (tendered_amount >= 0),
    CONSTRAINT ck_payment_allocation_change_non_negative
        CHECK (change_amount >= 0),
    CONSTRAINT ck_payment_allocation_change_consistency
        CHECK (change_amount = (tendered_amount - allocated_amount)),
    CONSTRAINT ck_payment_allocation_cash_or_card_rules
        CHECK (
            (tender_type = 'CASH' AND tendered_amount >= allocated_amount)
            OR (tender_type = 'CARD' AND tendered_amount = allocated_amount)
        )
);

CREATE INDEX IF NOT EXISTS idx_payment_allocation_payment_sequence
    ON payment_allocation (payment_id, sequence_number, id);
