CREATE TABLE IF NOT EXISTS sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    cashier_user_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    receipt_header_id BIGINT NOT NULL,
    receipt_number VARCHAR(80) NOT NULL,
    subtotal_net NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_tax NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_gross NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    rounding_adjustment NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_payable NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_cart
        FOREIGN KEY (cart_id) REFERENCES sale_cart (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_cashier_user
        FOREIGN KEY (cashier_user_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_terminal_device
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_cart UNIQUE (cart_id),
    CONSTRAINT uk_sale_receipt_number UNIQUE (receipt_number),
    CONSTRAINT ck_sale_subtotal_net_non_negative
        CHECK (subtotal_net >= 0),
    CONSTRAINT ck_sale_total_tax_non_negative
        CHECK (total_tax >= 0),
    CONSTRAINT ck_sale_total_gross_non_negative
        CHECK (total_gross >= 0),
    CONSTRAINT ck_sale_total_payable_non_negative
        CHECK (total_payable >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_store_created
    ON sale (store_location_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_sale_terminal_created
    ON sale (terminal_device_id, created_at, id);

CREATE TABLE IF NOT EXISTS sale_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    quantity NUMERIC(13, 3) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    net_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    gross_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    open_price_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_line_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_line_sale_number
        UNIQUE (sale_id, line_number),
    CONSTRAINT ck_sale_line_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT ck_sale_line_unit_price_non_negative
        CHECK (unit_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_line_sale_lookup
    ON sale_line (sale_id, line_number, id);

CREATE INDEX IF NOT EXISTS idx_sale_line_product_lookup
    ON sale_line (product_id, sale_id, id);

CREATE TABLE IF NOT EXISTS inventory_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sale_id BIGINT NOT NULL,
    sale_line_id BIGINT NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    quantity_delta NUMERIC(13, 3) NOT NULL,
    reference_number VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_movement_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movement_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movement_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_movement_sale_line
        FOREIGN KEY (sale_line_id) REFERENCES sale_line (id) ON DELETE CASCADE,
    CONSTRAINT ck_inventory_movement_type
        CHECK (movement_type IN ('SALE')),
    CONSTRAINT ck_inventory_movement_quantity_non_zero
        CHECK (quantity_delta <> 0),
    CONSTRAINT ck_inventory_movement_sale_quantity_negative
        CHECK (
            (movement_type = 'SALE' AND quantity_delta < 0)
        )
);

CREATE INDEX IF NOT EXISTS idx_inventory_movement_store_product_created
    ON inventory_movement (store_location_id, product_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_inventory_movement_sale_line
    ON inventory_movement (sale_line_id, id);
