ALTER TABLE payment
    ADD COLUMN status VARCHAR(20);

UPDATE payment
SET status = 'CAPTURED'
WHERE status IS NULL;

ALTER TABLE payment
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE payment
    ADD CONSTRAINT ck_payment_status
        CHECK (status IN ('AUTHORIZED', 'CAPTURED', 'VOIDED', 'REFUNDED'));

CREATE TABLE IF NOT EXISTS payment_transition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    actor_user_id BIGINT,
    actor_username VARCHAR(80) NOT NULL,
    note VARCHAR(255),
    correlation_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_transition_payment
        FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_transition_actor_user
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id),
    CONSTRAINT ck_payment_transition_action
        CHECK (action IN ('AUTHORIZE', 'CAPTURE', 'VOID', 'REFUND')),
    CONSTRAINT ck_payment_transition_from_status
        CHECK (from_status IS NULL OR from_status IN ('AUTHORIZED', 'CAPTURED', 'VOIDED', 'REFUNDED')),
    CONSTRAINT ck_payment_transition_to_status
        CHECK (to_status IN ('AUTHORIZED', 'CAPTURED', 'VOIDED', 'REFUNDED'))
);

CREATE INDEX IF NOT EXISTS idx_payment_transition_payment_created
    ON payment_transition (payment_id, created_at, id);
