CREATE TABLE IF NOT EXISTS sale_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    refund_tender_type VARCHAR(20) NOT NULL,
    refund_note VARCHAR(255),
    return_reference VARCHAR(80) NOT NULL,
    subtotal_net NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_tax NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_gross NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_return_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_return_payment
        FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE,
    CONSTRAINT uk_sale_return_reference UNIQUE (return_reference),
    CONSTRAINT ck_sale_return_reason_non_blank
        CHECK (length(trim(reason_code)) > 0),
    CONSTRAINT ck_sale_return_tender_type
        CHECK (refund_tender_type IN ('CASH', 'CARD')),
    CONSTRAINT ck_sale_return_subtotal_non_negative
        CHECK (subtotal_net >= 0),
    CONSTRAINT ck_sale_return_total_tax_non_negative
        CHECK (total_tax >= 0),
    CONSTRAINT ck_sale_return_total_gross_non_negative
        CHECK (total_gross >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_return_sale_created
    ON sale_return (sale_id, created_at, id);

CREATE TABLE IF NOT EXISTS sale_return_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id BIGINT NOT NULL,
    sale_line_id BIGINT NOT NULL,
    quantity NUMERIC(13, 3) NOT NULL,
    net_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    gross_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_return_line_return
        FOREIGN KEY (sale_return_id) REFERENCES sale_return (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_return_line_sale_line
        FOREIGN KEY (sale_line_id) REFERENCES sale_line (id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_return_line_return_sale_line
        UNIQUE (sale_return_id, sale_line_id),
    CONSTRAINT ck_sale_return_line_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT ck_sale_return_line_net_non_negative
        CHECK (net_amount >= 0),
    CONSTRAINT ck_sale_return_line_tax_non_negative
        CHECK (tax_amount >= 0),
    CONSTRAINT ck_sale_return_line_gross_non_negative
        CHECK (gross_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_return_line_sale_line
    ON sale_return_line (sale_line_id, sale_return_id, id);

CREATE TABLE IF NOT EXISTS sale_return_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    tender_type VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    reference VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_return_refund_return
        FOREIGN KEY (sale_return_id) REFERENCES sale_return (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_return_refund_payment
        FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE,
    CONSTRAINT ck_sale_return_refund_tender_type
        CHECK (tender_type IN ('CASH', 'CARD')),
    CONSTRAINT ck_sale_return_refund_amount_positive
        CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_return_refund_return
    ON sale_return_refund (sale_return_id, id);
