CREATE TABLE IF NOT EXISTS stock_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity_delta NUMERIC(13, 3) NOT NULL,
    reason_code VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    reference_number VARCHAR(80) NOT NULL,
    request_note VARCHAR(255),
    approval_note VARCHAR(255),
    post_note VARCHAR(255),
    requested_by VARCHAR(80) NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(80),
    approved_at TIMESTAMP,
    posted_by VARCHAR(80),
    posted_at TIMESTAMP,
    inventory_movement_id BIGINT,
    CONSTRAINT fk_stock_adjustment_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_adjustment_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_adjustment_movement
        FOREIGN KEY (inventory_movement_id) REFERENCES inventory_movement (id) ON DELETE SET NULL,
    CONSTRAINT uk_stock_adjustment_reference UNIQUE (reference_number),
    CONSTRAINT uk_stock_adjustment_inventory_movement UNIQUE (inventory_movement_id),
    CONSTRAINT ck_stock_adjustment_status
        CHECK (status IN ('PENDING_APPROVAL', 'APPROVED', 'POSTED')),
    CONSTRAINT ck_stock_adjustment_quantity_non_zero
        CHECK (quantity_delta <> 0),
    CONSTRAINT ck_stock_adjustment_reason_non_blank
        CHECK (length(trim(reason_code)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_adjustment_store_product_status
    ON stock_adjustment (store_location_id, product_id, status, requested_at, id);

CREATE INDEX IF NOT EXISTS idx_stock_adjustment_reference
    ON stock_adjustment (reference_number);
