CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_account_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT uk_app_role_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS app_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT uk_app_permission_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES app_role (id),
    CONSTRAINT uk_user_role_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES app_role (id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES app_permission (id),
    CONSTRAINT uk_role_permission_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_token_hash CHAR(64) NOT NULL,
    refresh_token_hash CHAR(64) NOT NULL,
    access_expires_at TIMESTAMP NOT NULL,
    refresh_expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT uk_auth_session_access_token_hash UNIQUE (access_token_hash),
    CONSTRAINT uk_auth_session_refresh_token_hash UNIQUE (refresh_token_hash)
);

CREATE TABLE IF NOT EXISTS auth_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    username VARCHAR(80) NULL,
    event_type VARCHAR(40) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    reason VARCHAR(255) NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_audit_event_user FOREIGN KEY (user_id) REFERENCES user_account (id)
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user ON auth_session (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_event_user ON auth_audit_event (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_event_occurred_at ON auth_audit_event (occurred_at);
