CREATE TABLE IF NOT EXISTS stocktake_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    reference_number VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    snapshot_at TIMESTAMP,
    note VARCHAR(255),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_by VARCHAR(80),
    started_at TIMESTAMP,
    finalized_by VARCHAR(80),
    finalized_at TIMESTAMP,
    CONSTRAINT fk_stocktake_session_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT uk_stocktake_session_reference UNIQUE (reference_number),
    CONSTRAINT ck_stocktake_session_status
        CHECK (status IN ('DRAFT', 'STARTED', 'FINALIZED'))
);

CREATE TABLE IF NOT EXISTS stocktake_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_session_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    expected_quantity NUMERIC(13, 3) NOT NULL DEFAULT 0,
    counted_quantity NUMERIC(13, 3),
    variance_quantity NUMERIC(13, 3),
    inventory_movement_id BIGINT,
    CONSTRAINT fk_stocktake_line_session
        FOREIGN KEY (stocktake_session_id) REFERENCES stocktake_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_line_movement
        FOREIGN KEY (inventory_movement_id) REFERENCES inventory_movement (id) ON DELETE SET NULL,
    CONSTRAINT uk_stocktake_line_session_product UNIQUE (stocktake_session_id, product_id),
    CONSTRAINT uk_stocktake_line_movement UNIQUE (inventory_movement_id),
    CONSTRAINT ck_stocktake_line_counted_non_negative
        CHECK (counted_quantity IS NULL OR counted_quantity >= 0),
    CONSTRAINT ck_stocktake_line_variance_pairing
        CHECK (
            (counted_quantity IS NULL AND variance_quantity IS NULL)
            OR
            (counted_quantity IS NOT NULL AND variance_quantity IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_stocktake_session_store_status
    ON stocktake_session (store_location_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_stocktake_line_session
    ON stocktake_line (stocktake_session_id, product_id);

ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_reference_type;
ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_source_document;

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_reference_type
        CHECK (reference_type IN ('SALE_RECEIPT', 'SALE_RETURN', 'STOCK_ADJUSTMENT', 'STOCKTAKE'));

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_source_document
        CHECK (
            (movement_type = 'SALE'
                AND sale_id IS NOT NULL
                AND sale_line_id IS NOT NULL
                AND quantity_delta < 0
                AND reference_type = 'SALE_RECEIPT')
            OR
            (movement_type = 'RETURN'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND quantity_delta > 0
                AND reference_type = 'SALE_RETURN')
            OR
            (movement_type = 'ADJUSTMENT'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND reference_type IN ('STOCK_ADJUSTMENT', 'STOCKTAKE'))
        );
