CREATE TABLE IF NOT EXISTS stock_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_store_location_id BIGINT NOT NULL,
    destination_store_location_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reference_number VARCHAR(80) NOT NULL,
    note VARCHAR(255),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shipped_by VARCHAR(80),
    shipped_at TIMESTAMP,
    received_by VARCHAR(80),
    received_at TIMESTAMP,
    CONSTRAINT fk_stock_transfer_source_store
        FOREIGN KEY (source_store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_transfer_destination_store
        FOREIGN KEY (destination_store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT uk_stock_transfer_reference UNIQUE (reference_number),
    CONSTRAINT ck_stock_transfer_status
        CHECK (status IN ('DRAFT', 'SHIPPED', 'PARTIALLY_RECEIVED', 'RECEIVED')),
    CONSTRAINT ck_stock_transfer_store_difference
        CHECK (source_store_location_id <> destination_store_location_id)
);

CREATE TABLE IF NOT EXISTS stock_transfer_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_transfer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    requested_quantity NUMERIC(13, 3) NOT NULL,
    shipped_quantity NUMERIC(13, 3),
    received_quantity NUMERIC(13, 3) NOT NULL DEFAULT 0,
    CONSTRAINT fk_stock_transfer_line_transfer
        FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfer (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_transfer_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uk_stock_transfer_line_transfer_product UNIQUE (stock_transfer_id, product_id),
    CONSTRAINT ck_stock_transfer_line_requested_positive
        CHECK (requested_quantity > 0),
    CONSTRAINT ck_stock_transfer_line_shipped_positive
        CHECK (shipped_quantity IS NULL OR shipped_quantity > 0),
    CONSTRAINT ck_stock_transfer_line_received_non_negative
        CHECK (received_quantity >= 0),
    CONSTRAINT ck_stock_transfer_line_received_requires_shipped
        CHECK (shipped_quantity IS NOT NULL OR received_quantity = 0),
    CONSTRAINT ck_stock_transfer_line_received_within_shipped
        CHECK (shipped_quantity IS NULL OR received_quantity <= shipped_quantity)
);

CREATE INDEX IF NOT EXISTS idx_stock_transfer_source_status
    ON stock_transfer (source_store_location_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_stock_transfer_destination_status
    ON stock_transfer (destination_store_location_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_stock_transfer_line_transfer
    ON stock_transfer_line (stock_transfer_id, product_id);

ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_reference_type;
ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_source_document;

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_reference_type
        CHECK (reference_type IN (
            'SALE_RECEIPT',
            'SALE_RETURN',
            'STOCK_ADJUSTMENT',
            'STOCKTAKE',
            'STOCK_TRANSFER_OUT',
            'STOCK_TRANSFER_IN'
        ));

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_source_document
        CHECK (
            (movement_type = 'SALE'
                AND sale_id IS NOT NULL
                AND sale_line_id IS NOT NULL
                AND quantity_delta < 0
                AND reference_type = 'SALE_RECEIPT')
            OR
            (movement_type = 'RETURN'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND quantity_delta > 0
                AND reference_type = 'SALE_RETURN')
            OR
            (movement_type = 'ADJUSTMENT'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND (
                    reference_type IN ('STOCK_ADJUSTMENT', 'STOCKTAKE')
                    OR (reference_type = 'STOCK_TRANSFER_OUT' AND quantity_delta < 0)
                    OR (reference_type = 'STOCK_TRANSFER_IN' AND quantity_delta > 0)
                ))
        );
