CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reference_number VARCHAR(80) NOT NULL,
    note VARCHAR(255),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(80),
    approved_at TIMESTAMP,
    last_received_by VARCHAR(80),
    last_received_at TIMESTAMP,
    CONSTRAINT fk_purchase_order_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT uk_purchase_order_reference UNIQUE (reference_number),
    CONSTRAINT ck_purchase_order_status
        CHECK (status IN ('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED'))
);

CREATE TABLE IF NOT EXISTS purchase_order_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    ordered_quantity NUMERIC(13, 3) NOT NULL,
    received_quantity NUMERIC(13, 3) NOT NULL DEFAULT 0,
    CONSTRAINT fk_purchase_order_line_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uk_purchase_order_line_order_product UNIQUE (purchase_order_id, product_id),
    CONSTRAINT ck_purchase_order_line_ordered_positive
        CHECK (ordered_quantity > 0),
    CONSTRAINT ck_purchase_order_line_received_non_negative
        CHECK (received_quantity >= 0),
    CONSTRAINT ck_purchase_order_line_received_within_ordered
        CHECK (received_quantity <= ordered_quantity)
);

CREATE TABLE IF NOT EXISTS goods_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    receipt_number VARCHAR(80) NOT NULL,
    received_by VARCHAR(80) NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(255),
    CONSTRAINT fk_goods_receipt_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id) ON DELETE CASCADE,
    CONSTRAINT uk_goods_receipt_number UNIQUE (receipt_number),
    CONSTRAINT ck_goods_receipt_number_non_blank
        CHECK (length(trim(receipt_number)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_supplier_status
    ON purchase_order (supplier_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_purchase_order_store_status
    ON purchase_order (store_location_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_purchase_order_line_order
    ON purchase_order_line (purchase_order_id, product_id);

CREATE INDEX IF NOT EXISTS idx_goods_receipt_order
    ON goods_receipt (purchase_order_id, received_at, id);

ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_reference_type;
ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_source_document;

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_reference_type
        CHECK (reference_type IN (
            'SALE_RECEIPT',
            'SALE_RETURN',
            'STOCK_ADJUSTMENT',
            'STOCKTAKE',
            'STOCK_TRANSFER_OUT',
            'STOCK_TRANSFER_IN',
            'PURCHASE_RECEIPT'
        ));

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_source_document
        CHECK (
            (movement_type = 'SALE'
                AND sale_id IS NOT NULL
                AND sale_line_id IS NOT NULL
                AND quantity_delta < 0
                AND reference_type = 'SALE_RECEIPT')
            OR
            (movement_type = 'RETURN'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND quantity_delta > 0
                AND reference_type = 'SALE_RETURN')
            OR
            (movement_type = 'ADJUSTMENT'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND (
                    reference_type IN ('STOCK_ADJUSTMENT', 'STOCKTAKE')
                    OR (reference_type = 'STOCK_TRANSFER_OUT' AND quantity_delta < 0)
                    OR (reference_type = 'STOCK_TRANSFER_IN' AND quantity_delta > 0)
                    OR (reference_type = 'PURCHASE_RECEIPT' AND quantity_delta > 0)
                ))
        );
