ALTER TABLE product
    ADD COLUMN IF NOT EXISTS lot_tracking_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS inventory_lot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    lot_code VARCHAR(80) NOT NULL,
    expiry_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_lot_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_lot_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT ck_inventory_lot_code_non_blank
        CHECK (length(trim(lot_code)) > 0),
    CONSTRAINT uk_inventory_lot_identity
        UNIQUE (store_location_id, product_id, lot_code, expiry_date)
);

CREATE INDEX IF NOT EXISTS idx_inventory_lot_store_product_expiry
    ON inventory_lot (store_location_id, product_id, expiry_date, id);

CREATE TABLE IF NOT EXISTS inventory_lot_balance (
    inventory_lot_id BIGINT PRIMARY KEY,
    quantity_on_hand NUMERIC(13, 3) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_lot_balance_lot
        FOREIGN KEY (inventory_lot_id) REFERENCES inventory_lot (id) ON DELETE CASCADE,
    CONSTRAINT ck_inventory_lot_balance_non_negative
        CHECK (quantity_on_hand >= 0)
);

CREATE TABLE IF NOT EXISTS inventory_movement_lot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_movement_id BIGINT NOT NULL,
    inventory_lot_id BIGINT NOT NULL,
    quantity NUMERIC(13, 3) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_movement_lot_movement
        FOREIGN KEY (inventory_movement_id) REFERENCES inventory_movement (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_movement_lot_lot
        FOREIGN KEY (inventory_lot_id) REFERENCES inventory_lot (id) ON DELETE RESTRICT,
    CONSTRAINT uk_inventory_movement_lot
        UNIQUE (inventory_movement_id, inventory_lot_id),
    CONSTRAINT ck_inventory_movement_lot_quantity_positive
        CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_inventory_movement_lot_movement
    ON inventory_movement_lot (inventory_movement_id, id);

CREATE INDEX IF NOT EXISTS idx_inventory_movement_lot_lot
    ON inventory_movement_lot (inventory_lot_id, id);

ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_source_document;

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_source_document
        CHECK (
            (movement_type = 'SALE'
                AND sale_id IS NOT NULL
                AND sale_line_id IS NOT NULL
                AND quantity_delta < 0
                AND reference_type = 'SALE_RECEIPT')
            OR
            (movement_type = 'RETURN'
                AND quantity_delta > 0
                AND reference_type = 'SALE_RETURN'
                AND (
                    (sale_id IS NULL AND sale_line_id IS NULL)
                    OR (sale_id IS NOT NULL AND sale_line_id IS NOT NULL)
                ))
            OR
            (movement_type = 'ADJUSTMENT'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND (
                    reference_type IN ('STOCK_ADJUSTMENT', 'STOCKTAKE')
                    OR (reference_type = 'STOCK_TRANSFER_OUT' AND quantity_delta < 0)
                    OR (reference_type = 'STOCK_TRANSFER_IN' AND quantity_delta > 0)
                    OR (reference_type = 'PURCHASE_RECEIPT' AND quantity_delta > 0)
                ))
        );
