CREATE TABLE IF NOT EXISTS inventory_product_cost (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    weighted_average_cost NUMERIC(13, 4) NOT NULL DEFAULT 0,
    last_cost NUMERIC(13, 4) NOT NULL DEFAULT 0,
    last_receipt_reference VARCHAR(80),
    last_movement_id BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_product_cost_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_product_cost_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_product_cost_last_movement
        FOREIGN KEY (last_movement_id) REFERENCES inventory_movement (id) ON DELETE SET NULL,
    CONSTRAINT uk_inventory_product_cost_identity
        UNIQUE (store_location_id, product_id),
    CONSTRAINT ck_inventory_product_cost_weighted_non_negative
        CHECK (weighted_average_cost >= 0),
    CONSTRAINT ck_inventory_product_cost_last_non_negative
        CHECK (last_cost >= 0)
);

CREATE INDEX IF NOT EXISTS idx_inventory_product_cost_store_product
    ON inventory_product_cost (store_location_id, product_id);
