CREATE TABLE IF NOT EXISTS supplier_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reference_number VARCHAR(80) NOT NULL,
    note VARCHAR(255),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(80),
    approved_at TIMESTAMP,
    posted_by VARCHAR(80),
    posted_at TIMESTAMP,
    CONSTRAINT fk_supplier_return_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_return_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_return_reference UNIQUE (reference_number),
    CONSTRAINT ck_supplier_return_status
        CHECK (status IN ('DRAFT', 'APPROVED', 'POSTED'))
);

CREATE TABLE IF NOT EXISTS supplier_return_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    return_quantity NUMERIC(13, 3) NOT NULL,
    unit_cost NUMERIC(16, 4) NOT NULL,
    inventory_movement_id BIGINT,
    CONSTRAINT fk_supplier_return_line_return
        FOREIGN KEY (supplier_return_id) REFERENCES supplier_return (id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_return_line_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_return_line_return_product UNIQUE (supplier_return_id, product_id),
    CONSTRAINT ck_supplier_return_line_quantity_positive
        CHECK (return_quantity > 0),
    CONSTRAINT ck_supplier_return_line_unit_cost_positive
        CHECK (unit_cost > 0)
);

CREATE INDEX IF NOT EXISTS idx_supplier_return_supplier_status
    ON supplier_return (supplier_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_supplier_return_store_status
    ON supplier_return (store_location_id, status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_supplier_return_line_return
    ON supplier_return_line (supplier_return_id, product_id);

ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_reference_type;
ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS ck_inventory_movement_source_document;

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_reference_type
        CHECK (reference_type IN (
            'SALE_RECEIPT',
            'SALE_RETURN',
            'STOCK_ADJUSTMENT',
            'STOCKTAKE',
            'STOCK_TRANSFER_OUT',
            'STOCK_TRANSFER_IN',
            'PURCHASE_RECEIPT',
            'SUPPLIER_RETURN'
        ));

ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_source_document
        CHECK (
            (movement_type = 'SALE'
                AND sale_id IS NOT NULL
                AND sale_line_id IS NOT NULL
                AND quantity_delta < 0
                AND reference_type = 'SALE_RECEIPT')
            OR
            (movement_type = 'RETURN'
                AND quantity_delta > 0
                AND reference_type = 'SALE_RETURN'
                AND (
                    (sale_id IS NULL AND sale_line_id IS NULL)
                    OR (sale_id IS NOT NULL AND sale_line_id IS NOT NULL)
                ))
            OR
            (movement_type = 'ADJUSTMENT'
                AND sale_id IS NULL
                AND sale_line_id IS NULL
                AND (
                    reference_type IN ('STOCK_ADJUSTMENT', 'STOCKTAKE')
                    OR (reference_type = 'STOCK_TRANSFER_OUT' AND quantity_delta < 0)
                    OR (reference_type = 'STOCK_TRANSFER_IN' AND quantity_delta > 0)
                    OR (reference_type = 'PURCHASE_RECEIPT' AND quantity_delta > 0)
                    OR (reference_type = 'SUPPLIER_RETURN' AND quantity_delta < 0)
                ))
        );
