CREATE TABLE IF NOT EXISTS idempotency_key_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_key VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    response_payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_idempotency_key_event_endpoint_key UNIQUE (endpoint_key, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_key_event_endpoint_created
    ON idempotency_key_event (endpoint_key, created_at, id);
