CREATE TABLE IF NOT EXISTS no_sale_drawer_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NULL,
    cashier_user_id BIGINT NULL,
    actor_user_id BIGINT NULL,
    actor_username VARCHAR(80) NULL,
    approved_by_user_id BIGINT NULL,
    approved_by_username VARCHAR(80) NULL,
    reason_code VARCHAR(40) NOT NULL,
    note VARCHAR(255) NULL,
    correlation_id VARCHAR(100) NULL,
    reference_number VARCHAR(120) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_no_sale_drawer_event_store_location
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_no_sale_drawer_event_terminal
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE SET NULL,
    CONSTRAINT fk_no_sale_drawer_event_cashier
        FOREIGN KEY (cashier_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_no_sale_drawer_event_actor
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_no_sale_drawer_event_approved_by
        FOREIGN KEY (approved_by_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT ck_no_sale_drawer_event_reason_non_blank
        CHECK (length(trim(reason_code)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_no_sale_drawer_event_created
    ON no_sale_drawer_event (created_at, id);

CREATE INDEX IF NOT EXISTS idx_no_sale_drawer_event_filters
    ON no_sale_drawer_event (store_location_id, terminal_device_id, cashier_user_id, reason_code);
