INSERT INTO app_permission (code, description)
SELECT 'RECEIPT_REPRINT', 'Allows receipt reprint and receipt journal retrieval operations'
WHERE NOT EXISTS (SELECT 1 FROM app_permission WHERE code = 'RECEIPT_REPRINT');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM app_role r
JOIN app_permission p ON p.code = 'RECEIPT_REPRINT'
WHERE r.code = 'MANAGER'
  AND NOT EXISTS (
    SELECT 1
    FROM role_permission rp
    WHERE rp.role_id = r.id
      AND rp.permission_id = p.id
);

CREATE TABLE IF NOT EXISTS receipt_print_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    receipt_header_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    actor_user_id BIGINT NULL,
    actor_username VARCHAR(80) NOT NULL,
    is_copy BOOLEAN NOT NULL,
    adapter VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    retryable BOOLEAN NOT NULL,
    message VARCHAR(255) NULL,
    correlation_id VARCHAR(100) NULL,
    printed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipt_print_event_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_print_event_store
        FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_print_event_terminal
        FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_print_event_actor
        FOREIGN KEY (actor_user_id) REFERENCES user_account (id) ON DELETE SET NULL,
    CONSTRAINT ck_receipt_print_event_actor_non_blank
        CHECK (length(trim(actor_username)) > 0),
    CONSTRAINT ck_receipt_print_event_status
        CHECK (status IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_receipt_print_event_adapter_non_blank
        CHECK (length(trim(adapter)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_receipt_print_event_sale_printed
    ON receipt_print_event (sale_id, printed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_receipt_print_event_receipt_header_printed
    ON receipt_print_event (receipt_header_id, printed_at DESC, id DESC);
