CREATE TABLE IF NOT EXISTS merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_merchant_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS store_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_location_merchant FOREIGN KEY (merchant_id) REFERENCES merchant (id),
    CONSTRAINT uk_store_location_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS terminal_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_terminal_device_store_location FOREIGN KEY (store_location_id) REFERENCES store_location (id),
    CONSTRAINT uk_terminal_device_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS store_user_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_user_assignment_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT fk_store_user_assignment_store_location FOREIGN KEY (store_location_id) REFERENCES store_location (id),
    CONSTRAINT fk_store_user_assignment_role FOREIGN KEY (role_id) REFERENCES app_role (id),
    CONSTRAINT uk_store_user_assignment_user_store_role UNIQUE (user_id, store_location_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_store_location_merchant ON store_location (merchant_id);
CREATE INDEX IF NOT EXISTS idx_terminal_device_store_location ON terminal_device (store_location_id);
CREATE INDEX IF NOT EXISTS idx_store_user_assignment_user ON store_user_assignment (user_id);
CREATE INDEX IF NOT EXISTS idx_store_user_assignment_store_location ON store_user_assignment (store_location_id);
CREATE INDEX IF NOT EXISTS idx_store_user_assignment_role ON store_user_assignment (role_id);
