ALTER TABLE sale
    ADD COLUMN IF NOT EXISTS invoice_required BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS fiscal_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT,
    sale_return_id BIGINT,
    document_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    provider_code VARCHAR(40) NOT NULL,
    external_document_id VARCHAR(120),
    request_reference VARCHAR(80) NOT NULL,
    message VARCHAR(255),
    issued_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fiscal_document_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE,
    CONSTRAINT fk_fiscal_document_sale_return
        FOREIGN KEY (sale_return_id) REFERENCES sale_return (id) ON DELETE CASCADE,
    CONSTRAINT ck_fiscal_document_type
        CHECK (document_type IN ('INVOICE', 'CREDIT_NOTE')),
    CONSTRAINT ck_fiscal_document_status
        CHECK (status IN ('ISSUED', 'CANCELLED', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_fiscal_document_context
        CHECK (
            (sale_id IS NOT NULL AND sale_return_id IS NULL)
            OR (sale_id IS NOT NULL AND sale_return_id IS NOT NULL)
        ),
    CONSTRAINT uk_fiscal_document_sale_type
        UNIQUE (sale_id, document_type),
    CONSTRAINT uk_fiscal_document_sale_return_type
        UNIQUE (sale_return_id, document_type)
);

CREATE INDEX IF NOT EXISTS idx_fiscal_document_sale
    ON fiscal_document (sale_id, document_type, id);

CREATE INDEX IF NOT EXISTS idx_fiscal_document_sale_return
    ON fiscal_document (sale_return_id, document_type, id);

CREATE TABLE IF NOT EXISTS fiscal_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_document_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    message VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fiscal_event_document
        FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_document (id) ON DELETE CASCADE,
    CONSTRAINT ck_fiscal_event_type
        CHECK (event_type IN (
            'ISSUE_SUCCEEDED',
            'ISSUE_FAILED',
            'ISSUE_SKIPPED',
            'CANCEL_SUCCEEDED',
            'CANCEL_FAILED',
            'CREDIT_NOTE_SUCCEEDED',
            'CREDIT_NOTE_FAILED'
        ))
);

CREATE INDEX IF NOT EXISTS idx_fiscal_event_document_created
    ON fiscal_event (fiscal_document_id, created_at, id);
