CREATE TABLE IF NOT EXISTS gift_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    card_number VARCHAR(40) NOT NULL,
    card_number_normalized VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    issued_amount NUMERIC(14, 2) NOT NULL,
    balance_amount NUMERIC(14, 2) NOT NULL,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gift_card_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_gift_card_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT,
    CONSTRAINT uk_gift_card_merchant_number
        UNIQUE (merchant_id, card_number_normalized),
    CONSTRAINT ck_gift_card_status
        CHECK (status IN ('ACTIVE', 'EXHAUSTED')),
    CONSTRAINT ck_gift_card_issued_amount_positive
        CHECK (issued_amount > 0),
    CONSTRAINT ck_gift_card_balance_non_negative
        CHECK (balance_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_gift_card_customer
    ON gift_card (customer_id, id);

CREATE TABLE IF NOT EXISTS gift_card_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_card_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    balance_before NUMERIC(14, 2) NOT NULL,
    balance_after NUMERIC(14, 2) NOT NULL,
    sale_id BIGINT,
    sale_return_id BIGINT,
    reference VARCHAR(80),
    note VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gift_card_transaction_card
        FOREIGN KEY (gift_card_id) REFERENCES gift_card (id) ON DELETE CASCADE,
    CONSTRAINT fk_gift_card_transaction_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE RESTRICT,
    CONSTRAINT fk_gift_card_transaction_sale_return
        FOREIGN KEY (sale_return_id) REFERENCES sale_return (id) ON DELETE RESTRICT,
    CONSTRAINT ck_gift_card_transaction_type
        CHECK (transaction_type IN ('ISSUE', 'REDEEM')),
    CONSTRAINT ck_gift_card_transaction_amount_positive
        CHECK (amount > 0),
    CONSTRAINT ck_gift_card_transaction_balances_non_negative
        CHECK (balance_before >= 0 AND balance_after >= 0),
    CONSTRAINT ck_gift_card_redeem_context
        CHECK (
            (transaction_type = 'ISSUE' AND sale_id IS NULL AND sale_return_id IS NULL)
            OR (
                transaction_type = 'REDEEM'
                AND ((sale_id IS NOT NULL AND sale_return_id IS NULL) OR (sale_id IS NULL AND sale_return_id IS NOT NULL))
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_gift_card_transaction_card_created
    ON gift_card_transaction (gift_card_id, created_at, id);
