CREATE TABLE IF NOT EXISTS store_credit_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    balance_amount NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_credit_account_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_store_credit_account_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT,
    CONSTRAINT uk_store_credit_account_merchant_customer
        UNIQUE (merchant_id, customer_id),
    CONSTRAINT ck_store_credit_account_balance_non_negative
        CHECK (balance_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_store_credit_account_customer
    ON store_credit_account (customer_id, id);

CREATE TABLE IF NOT EXISTS store_credit_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_credit_account_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    balance_before NUMERIC(14, 2) NOT NULL,
    balance_after NUMERIC(14, 2) NOT NULL,
    sale_id BIGINT,
    sale_return_id BIGINT,
    reference VARCHAR(80),
    note VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_credit_transaction_account
        FOREIGN KEY (store_credit_account_id) REFERENCES store_credit_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_store_credit_transaction_sale
        FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE RESTRICT,
    CONSTRAINT fk_store_credit_transaction_sale_return
        FOREIGN KEY (sale_return_id) REFERENCES sale_return (id) ON DELETE RESTRICT,
    CONSTRAINT ck_store_credit_transaction_type
        CHECK (transaction_type IN ('ISSUE', 'REDEEM')),
    CONSTRAINT ck_store_credit_transaction_amount_positive
        CHECK (amount > 0),
    CONSTRAINT ck_store_credit_transaction_balances_non_negative
        CHECK (balance_before >= 0 AND balance_after >= 0),
    CONSTRAINT ck_store_credit_issue_redeem_context
        CHECK (
            (transaction_type = 'ISSUE' AND sale_return_id IS NOT NULL AND sale_id IS NULL)
            OR (transaction_type = 'REDEEM' AND sale_id IS NOT NULL AND sale_return_id IS NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_store_credit_transaction_account_created
    ON store_credit_transaction (store_credit_account_id, created_at, id);
