CREATE TABLE IF NOT EXISTS cash_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_user_id BIGINT NOT NULL,
    terminal_device_id BIGINT NOT NULL,
    store_location_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    opening_cash NUMERIC(14, 2) NOT NULL,
    total_paid_in NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_paid_out NUMERIC(14, 2) NOT NULL DEFAULT 0,
    expected_close_cash NUMERIC(14, 2) NULL,
    counted_close_cash NUMERIC(14, 2) NULL,
    variance_cash NUMERIC(14, 2) NULL,
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_shift_cashier_user FOREIGN KEY (cashier_user_id) REFERENCES user_account (id),
    CONSTRAINT fk_cash_shift_terminal_device FOREIGN KEY (terminal_device_id) REFERENCES terminal_device (id),
    CONSTRAINT fk_cash_shift_store_location FOREIGN KEY (store_location_id) REFERENCES store_location (id),
    CONSTRAINT ck_cash_shift_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_cash_shift_opening_non_negative CHECK (opening_cash >= 0),
    CONSTRAINT ck_cash_shift_totals_non_negative CHECK (total_paid_in >= 0 AND total_paid_out >= 0),
    CONSTRAINT ck_cash_shift_close_consistency CHECK (
        (status = 'OPEN' AND closed_at IS NULL AND expected_close_cash IS NULL
            AND counted_close_cash IS NULL AND variance_cash IS NULL)
        OR
        (status = 'CLOSED' AND closed_at IS NOT NULL AND expected_close_cash IS NOT NULL
            AND counted_close_cash IS NOT NULL AND variance_cash IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS cash_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    note VARCHAR(255) NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_movement_shift FOREIGN KEY (shift_id) REFERENCES cash_shift (id),
    CONSTRAINT ck_cash_movement_type CHECK (movement_type IN ('OPEN', 'PAID_IN', 'PAID_OUT', 'CLOSE')),
    CONSTRAINT ck_cash_movement_amount_non_negative CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_cash_shift_cashier_terminal_status
    ON cash_shift (cashier_user_id, terminal_device_id, status);
CREATE INDEX IF NOT EXISTS idx_cash_shift_store_location_status
    ON cash_shift (store_location_id, status);
CREATE INDEX IF NOT EXISTS idx_cash_movement_shift
    ON cash_movement (shift_id);
CREATE INDEX IF NOT EXISTS idx_cash_movement_occurred_at
    ON cash_movement (occurred_at);
