ALTER TABLE product
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(14, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE product
    ADD CONSTRAINT ck_product_base_price_non_negative CHECK (base_price >= 0);

CREATE TABLE IF NOT EXISTS price_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    effective_from TIMESTAMP NULL,
    effective_to TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_book_merchant FOREIGN KEY (merchant_id) REFERENCES merchant (id) ON DELETE CASCADE,
    CONSTRAINT uk_price_book_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT ck_price_book_effective_window CHECK (
        effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to
    )
);

CREATE TABLE IF NOT EXISTS price_book_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_book_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    price NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_book_item_price_book FOREIGN KEY (price_book_id) REFERENCES price_book (id) ON DELETE CASCADE,
    CONSTRAINT fk_price_book_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uk_price_book_item_price_book_product UNIQUE (price_book_id, product_id),
    CONSTRAINT ck_price_book_item_price_non_negative CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS store_price_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    price NUMERIC(14, 2) NOT NULL,
    effective_from TIMESTAMP NULL,
    effective_to TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_price_override_store_location FOREIGN KEY (store_location_id) REFERENCES store_location (id) ON DELETE CASCADE,
    CONSTRAINT fk_store_price_override_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT ck_store_price_override_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_store_price_override_effective_window CHECK (
        effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to
    )
);

CREATE INDEX IF NOT EXISTS idx_price_book_merchant_active_window
    ON price_book (merchant_id, is_active, effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_price_book_item_product
    ON price_book_item (product_id);
CREATE INDEX IF NOT EXISTS idx_store_price_override_store_product_window
    ON store_price_override (store_location_id, product_id, is_active, effective_from, effective_to);
